apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-argocd-application-controller
  namespace: phpinfo-helm-javinotfound
rules:
  - apiGroups:
      - ''
    verbs:
      - create
      - patch
    resources:
      - services
  - apiGroups:
      - apps
    verbs:
      - create
      - patch # Added because we need this role to make modifications 
    resources:
      - deployments
# Added this apiGroup rule because we need grant to argocd can create rules
  - apiGroups:
      - route.openshift.io
    verbs:
      - create
    resources:
      - routes
