
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "phpinfo.fullname" . }}
  labels:
    {{- include "phpinfo.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "phpinfo.fullname" . }}

