
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpinfo.fullname" . }}
  labels:
    {{- include "phpinfo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "phpinfo.selectorLabels" . | nindent 4 }}

