apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phpinfo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phpinfo
  minReplicas: 3
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 50
          type: Utilization
