apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-argocd-application-controller
rules:
  - apiGroups:
      - ''
    verbs:
      - create
      - delete # Added because ArgoCD needs this role to prune svc2.
      - patch
    resources:
      - services
  - apiGroups:
      - apps
    verbs:
      - create
      - patch
    resources:
      - deployments
  - apiGroups:
      - route.openshift.io
    verbs:
      - create
    resources:
      - routes
