apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpinfo-helm-javinotfound-2
spec:
  destination:
    namespace: phpinfo-helm-javinotfound-2
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: master/course/dev/phpinfo/helm2
    repoURL: https://github.com/javinotfound/openshift.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
