namespace: phpinfo-helm-javinotfound-2
svc:
  - name: svc
    ports:
      - port: 5050
    selector:
      app: deploy
  #- name: svc2 # This svc is NOT used, is an example
  #  ports:
  #    - port: 6060
  #  selector:
  #    app: deploy2
routes:
 - name: route
   tls:
     insecureEdgeTerminationPolicy: Redirect
     termination: edge
   to:
     kind: Service
     name: svc
